server:
  port: 8080

#spring:
#  jpa:
#    hibernate:
#      ddl-auto: none
#  datasource:
#    url: jdbc:mysql://localhost:3307/
#    username:
#    password:
#    driver-class-name: com.mysql.cj.jdbc.Driver

#jwt:
#  private-key: tK9A7PuWgGGS1BJOzFbdtgUoUX3H8ngwB8ZoX/AAcYo=

path:
  data: 

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

gemini:
  api-key: 

#redis:
#  host: localhost
#  port: 6379
